### ISSUE TITLE
Dates are incorrect

### ISSUE THREAD

**Issue by clrvynt** [mmick66/CalendarView#1]
I'm not sure if this is actively maintained, but running the project cloned out of github shows the wrong dates ..

For example, running it today (April 23rd) highlights March 24th as "today". The days are all lined up incorrectly as well. It says that January 1st is a Sunday.

**Comment by mmick66** [comment]
It is actively maintained... I will look into it tomorrow...

**Comment by clrvynt** [comment]
Hi @mmick66 

Thanks! I was able to work past the issue -- it was basically happening because of the GMT Calendar .. I'm in the Eastern timezone in the US and this was causing a weird offset . 


Changing the GMT calendar to use NSCalendar.currentCalendar fixed the issue. 

You can reproduce the issue by changing your computers' timezone to Eastern and also setting the time to late evening ( after 9pm ).

**Comment by mmick66** [comment]
Wow... Thanks... Do you think you could do a pull request so I can merge the code?
