### ISSUE TITLE
Retrieving Cell date within UICollectionView - Cell for item at index

### ISSUE THREAD

**Issue by aldertc** [mmick66/CalendarView#10]
I would like to get the cell date from within the UICollectionView - cell for item at index path, as dependant on certain dates I want to do something. These are not events so this is why I am not flagging them that way. I simply have a list of dates which for those dates I wish to change the cell colour.

Changing the cell colour I can do but I am having trouble retrieving the date accurately.

Within this function (UICollectionView CellForItemAtIndex - I did add this code, which seems ok apart from if you change your timezone. So within GMT/UTC it works fine but as soon as I move out to say EST then the cell date being returned is incorrect.

let firstDayInMonth = currentMonthInfo[0]
var offsetComponents = DateComponents()
offsetComponents.month = indexPath.section
offsetComponents.day = indexPath.item - firstDayInMonth
var cellDate = (Calendar.current as NSCalendar).date(byAdding: offsetComponents, to: self.startOfMonthCache, options: NSCalendar.Options())

Any thoughts what I am doing wrong?

**Comment by mmick66** [comment]
So you want to retrieve an array of the type `[IndexPath]`, am I correct?

**Comment by mohsinka** [comment]
@aldertc can you explain how you changed the color of the cells. I'd like to do the same for a certain set of dates all across the year. Any help is more than appreciated.
