### ISSUE TITLE
Cannot access selectedDates

### ISSUE THREAD

**Issue by ivrylobs** [mmick66/CalendarView#101]
Error said it's internal var ? But actually it could be access as public right ?
Need help!!!

**Comment by mmick66** [comment]
Did you install via Coco pods?

**Comment by ivrylobs** [comment]
> Did you install via Coco pods?

Yes, i did .
It's work now , i have unlocked the CalendarView file and change its declaration of the variable from internal to public.

**Comment by ivrylobs** [comment]
But still don't know why internal var is its declaration at first to access it it'd be public right?

**Comment by mmick66** [comment]
I just updated the Pod to 1.8.3. Please check this one and let me know. Failing this, please install the calendar manually, which is simply by dragging the folder to your project. Let me know how it went.

**Comment by ivrylobs** [comment]
It's work perfectly now thank you sir
