### ISSUE TITLE
Date is incorrect

### ISSUE THREAD

**Issue by thejarlid** [mmick66/CalendarView#104]
the current date based on the user's locale is incorrect beginning with the new year. When giving the current date in GMT format in the data source StartDate method, the date selected on the calendar is incorrect instead selecting the date for GMT time.

**Comment by mmick66** [comment]
I will have a look ASAP.

**Comment by thejarlid** [comment]
A bit of debugging help, I'm able to replicate this in the demo app. I'm in PST and the date highlighted on the calendar is correct while GMT and PST are on the same day. The date returned from selecting a date is also off when this is the case. 

For example it is currently Jan 2nd, 2020 20:01 PST, but the highlighted date on the calendar when start date returns Date() is Jan 3rd. If I select Jan 3rd on the calendar the delegate method returns Jan 2nd. I haven't had a whole lot of time to dive into the code directly, however it seems like the date is not converted to the current locale when set up.

**Comment by mmick66** [comment]
Could you zip your project and send it here?

**Comment by thejarlid** [comment]
Its not specific to my project in particular, I was able to reproduce it by cloning the repo and running the demo app provided

**Comment by mmick66** [comment]
Sorry for such a late reply. I have pushed a change. My rational is that the only thing needed to change is what is shown as "today," as countries in zones other than UTC would cross over to the next day in different UTC-relative times. Please let me know if that works for you and feel free to reopen the issue.

**Comment by thejarlid** [comment]
Hey, I don't believe this fixed the issue. The date returned when a date is selected is in UTC however, the user interacting with the calendar is interacting with the presented calendar in their current locale. So from their perspective they click on the date they want however the date returned from the method is not the date they want. I am experiencing this in PST. If I select Feb 26th on the calendar I get Feb 26th in UTC back but when I attempt to print it out with the current user's locale or do any work with the current locale the date changes to the wrong date which is not what someone interacting with the calendar expected.
