### ISSUE TITLE
Crash app when create Calendar

### ISSUE THREAD

**Issue by kilirushi** [mmick66/CalendarView#107]
![Screen Shot 2020-01-18 at 20 41 07](https://user-images.githubusercontent.com/17327812/72664682-367b1300-3a33-11ea-81b0-9d900560907d.png)

**Comment by kilirushi** [comment]
I think I should change it to: TimeZone(secondsFromGMT: TimeZone.current.secondsFromGMT())

**Comment by mmick66** [comment]
Wow... I changed that very recently. Can you please do one of the following (or even both).
1. Send me a zip of your project.
2. Tell me if you fixed it and how...
