### ISSUE TITLE
RTL languages problems

### ISSUE THREAD

**Issue by Black-Colt** [mmick66/CalendarView#11]
On RTL languages the calendar starts from the distance future.

**Comment by mmick66** [comment]
Can you please zip your project and sent it to me to have a look?

**Comment by Black-Colt** [comment]
Yes, Where to send it to?

**Comment by mmick66** [comment]
Zip it and drag it here...

**Comment by Black-Colt** [comment]
I found the problem.
If you change the development language to another language its behaving strange).
[test.zip](https://github.com/mmick66/CalendarView/files/847207/test.zip)

I made a test app for you to see (You can see that even the month above not showing until you scroll swipe the calendar.
