### ISSUE TITLE
There is a small problem with the deselect delegate

### ISSUE THREAD

**Issue by chaoxinzheng** [mmick66/CalendarView#12]
The bold text need to be included in the line to make sure that the de-selecting of the days return the right de-selected days. Otherwise, it always returns the last selected days.
 
   func collectionView(_ collectionView: UICollectionView, didDeselectItemAt indexPath: IndexPath) {
        
        guard let dateBeingSelectedByUser = dateBeingSelectedByUser else {
            return
        }
        
        guard let index = selectedIndexPaths.index(of: indexPath) else {
            return
        }

        delegate?.calendar?(self, didDeselectDate: dateBeingSelectedByUser)

        selectedIndexPaths.remove(at: index)
        selectedDates.remove(at: index)
        
        **self.dateBeingSelectedByUser = selectedDates.last**
        
    }

**Comment by mmick66** [comment]
Thank you very much for this. The change has been incorporated.
