### ISSUE TITLE
Adding Next and Previous Month functionality results in garbled dates

### ISSUE THREAD

**Issue by caprahul** [mmick66/CalendarView#16]
I tried to implement next and previous month functionality in my custom class **EventViewController** by adding the following function in **CalendarView** class

```
    func moveCalendarToDate(date: Date) {
        if let indexPathForDate = indexPathForDate(date) {
            calendarView.scrollToItem(at: indexPathForDate, at: .centeredHorizontally, animated: true)
        }
    }

```

where I manually calculate the next and previous month dates in code using 
Inside  **EventViewController**, I have following method to call method on calendarView

       func moveCalendar(byAdvance advance: CalendarMonthAdvanceType, fromDate date: Date) -> 
        Date? {
        var nextDate: Date?
        
        // This is the current date in view and user wants to move to next month
        let calendar = Calendar.current
        
        nextDate = calendar.date(byAdding: .month, value: 1, to: date)
        
        let unitFlags = Set<Calendar.Component>([.year, .month])
        calendar.timeZone = TimeZone(identifier: "UTC")!
        
        let components = calendar.dateComponents(unitFlags, from: nextDate!)
        nextDate = calendar.date(from: components)!
        
        calendarView.moveCalendarToDate(date: nextDate!)

        return nextDate
    }

    enum CalendarMonthAdvanceType: Int {
        case previous = -1
        case next = 1
    }

However calling this method has weird implications where all dates are shifted by one column. I have tried going over the code over and over again but most probably I am missing something pretty small. Could you please take a look and add some pointers to help me fix this. 

Screenshot attached for view hierarchy.

**Normal calendar view For July 2017**
![july-2017-calendar](https://user-images.githubusercontent.com/648694/27838472-14038f26-60a8-11e7-8c83-e1793dc2ba4a.png)

**Distorted calendar view for August 2017**
![august-2017-calendar](https://user-images.githubusercontent.com/648694/27838470-1401b53e-60a8-11e7-85a4-e231dc6f472a.png)

**View hierarchy as captured via XCode**

![view-hierarchy](https://user-images.githubusercontent.com/648694/27838471-1402f9c6-60a8-11e7-85a8-6d855f872ef7.png)

**Comment by david2Coders** [comment]
The CalendarView has a method which will scroll to the given date         
` self.calendarView.setDisplayDate(date, animated: true)
`
