### ISSUE TITLE
Calendar is Crashing in IOS10

### ISSUE THREAD

**Issue by nagaraju85** [mmick66/CalendarView#18]
Calender is working fine in ios9 it's showing the events also,
when I can run this code in Ios10  application is crashing 
After this calling it's crashing 

            newCalendar.source = sourcesInEventStore.filter{
                (source: EKSource) -> Bool in
                source.sourceType.rawValue == EKSourceType.local.rawValue
             }.first!

**Comment by mmick66** [comment]
New commit with updated code.
