### ISSUE TITLE
Month label goes under the navigation bar

### ISSUE THREAD

**Issue by hamidgh** [mmick66/CalendarView#2]
Steps to reproduce:
1-In the current example of the project if you go to the storyboard and select the View Controller and put it under a navigation controller from Editor/Embed In/Navigation Controller. It adds navigation controller to the view but you will get a warning from CalendarView constraints. It wants to move down the view (Like bellow Screenshot). 
![s1](https://cloud.githubusercontent.com/assets/2271701/14944740/a0cbf994-0fc2-11e6-910f-c0b21e0719fe.png)
If you fix the warning based on the suggestion, it moves down the view and warning goes away (Like bellow screenshot).

![s2](https://cloud.githubusercontent.com/assets/2271701/14944758/81b3150a-0fc3-11e6-8232-ee71d9bfb34e.png)

But at runtime, month label goes completely under the navigation bar like bellow screenshot.
![screen shot 2016-05-01 at 5 39 03 pm](https://cloud.githubusercontent.com/assets/2271701/14944760/9d0ba7b8-0fc3-11e6-8d0b-2a63210ecbb3.png)

**Comment by mmick66** [comment]
This is a navigation controller issue, not a calendar issue. It is solved here : http://stackoverflow.com/questions/18789225/ios-7-uinavigationbar-uiview-layout-issue
