### ISSUE TITLE
Selected Date dissapear after page scrolling

### ISSUE THREAD

**Issue by brizzly** [mmick66/CalendarView#21]
FYI -- Just fixed this issue by swapping lines here 

    func selectDate(_ date : Date) {
        
        guard let indexPath = self.indexPathForDate(date) else {
            return
        }

// Put this one *BEFORE*
		self.calendarView.selectItem(at: indexPath, animated: false, scrollPosition: UICollectionViewScrollPosition())

        guard self.calendarView.indexPathsForSelectedItems?.contains(indexPath) == false else {
            return
		}

**Comment by mmick66** [comment]
Done! Thanks!
