### ISSUE TITLE
month-1 does nothing sometimes

### ISSUE THREAD

**Issue by brizzly** [mmick66/CalendarView#22]
There is an issue when you call previous month method, sometimes it does not go to the desired month-1.

Here is an ugly fix based on previous code..

	func setDisplayDate(_ date : Date, animated: Bool) {
		
		if let dispDate = self.displayDate {
			
			// skip is we are trying to set the same date
			if  date.compare(dispDate) == ComparisonResult.orderedSame {
				return
			}
			
			// check if the date is within range
			
			if startDateCache == date {
				return
			}
			if let startDateCache2 = self.calendar.date(byAdding: .month, value: -1, to: startDateCache) {
				if  date.compare(startDateCache2) == ComparisonResult.orderedAscending {
					return
				}
			}
			else
			{
				if  date.compare(startDateCache) == ComparisonResult.orderedAscending {
					return
				}
			}
			
			if  date.compare(endDateCache) == ComparisonResult.orderedDescending   {
				return
			}
			
			
			self.collectionView.setContentOffset(
				self.scrollViewOffset(in: self.collectionView, for: date),
				animated: animated
			)
			
		}
		
	}

    /*
	func setDisplayDate(_ date : Date, animated: Bool) {
		
		// Julien
		if date == startDateCache {
			return
		}
		let newStartDateCache = self.calendar.date(byAdding: .month, value: -1, to: startDateCache)

			
		guard (date > newStartDateCache!) && (date < endDateCache) else { return }
		
		self.collectionView.setContentOffset(
			self.scrollViewOffset(in: self.collectionView, for: date),
			animated: animated
		)
		
		self.displayDateOnHeader(date)
		
	}
	*/

**Comment by mmick66** [comment]
I checked and I cannot reproduce the problem. Please let me know exactly which dates are you setting as start and end and I will try to replicate it on my side. Please check the latest code as I made some changes. And above all thank you for using my code.

**Comment by brizzly** [comment]
I'm sure there is a bug lol. I have fixed into my code. Swip back is working but not when you call previousMonth method, you stuck 1 month after.

**Comment by mmick66** [comment]
Like I said above, can you let me know exactly which dates are you setting in your data source and I will try to replicate it on my side?

**Comment by brizzly** [comment]
any date.. let say  :  25/10/17

**Comment by mmick66** [comment]
Can you please copy and paste the code from your delegate that returns the start **and** end?

**Comment by mmick66** [comment]
Can you please zip your project and drop it here so I can have a look?
