### ISSUE TITLE
All your code have "internal" access. Can't use as pod library

### ISSUE THREAD

**Issue by maksymhusar** [mmick66/CalendarView#27]

**Comment by czater** [comment]
same here

**Comment by hyouuu** [comment]
+1

**Comment by mmick66** [comment]
Hi, I am not familiar with this issue. Can you please elaborate? Pods is not my strong point.

**Comment by maksymhusar** [comment]
Hi! You should set to all properties 'open' or 'public' access modifier for
using it as 3d part library. By default all what you have in .swift files
have 'internal' modifier.
Hope this short explanation will help.

2018-01-08 14:54 GMT+02:00 Michael Michailidis <notifications@github.com>:

**Comment by mmick66** [comment]
I edited the classes to be "open" and made the changes required to support that.
