### ISSUE TITLE
Calendar View not loading the endDate() month

### ISSUE THREAD

**Issue by atticmanatee** [mmick66/CalendarView#28]
Let me just say I freaking love this library, thanks for it man!

Now, to the issue:
My App is loading an array of events from the Graph API, and I just want to show the calendar up to the month of the last event. So if the last event is on the 7th of March and we're in January, I want to have January, February and March showing up.

I come across this issue where the last month of calendar is not being shown, and in order for it show I have to add enough days to the endDate().

Eg.:
` func endDate() -> Date {
        var calendarEndDate = Date()
        print("Current Date: \(calendarEndDate)")
        
        for event in events.list {
            print("Evaluating: \(event.startTime!)")
            if event.startTime > calendarEndDate {
                calendarEndDate = event.startTime
            }
        }
        print("Calendar End Date: \(calendarEndDate)")
        
        var dateComponents = DateComponents()
        dateComponents.day = +6
        
        calendarEndDate = self.calendarView.calendar.date(byAdding: dateComponents, to: calendarEndDate)!
        print("Fixed endDate: \(calendarEndDate)")
        return calendarEndDate
    }`

if the last event is on the 7th of March, without adding 6 more day to the end date, I could not see March in the Calendar.

Not sure if this is a bug, or working as intended, but the workaround I found was jut to add 13 days to the end date, in order to pass the threshold of the day 12 which is when it starts showing the calendar.

Once again, thanks for the awesome library!

**Comment by mmick66** [comment]
Thanks for discovering this bug. Please try and comment if something went wrong with the refactoring.
