### ISSUE TITLE
Starting month display

### ISSUE THREAD

**Issue by aldertc** [mmick66/CalendarView#3]
Not really an issue but a request for having an option to select the calendar display start month. So currently I have it in my app with 6 months history but at the moment the calendar starts by displaying the very first month when I would rather have it always start with the current month and then I can choose to page back 6 months.

Is this something you could easily add to your code or have a suggestion as how best to achieve? I have played around trying to use 'scrollToItemAtIndexPath' but with no success so any help would be gratefully appreciated.

Many thanks,

Carl

**Comment by mmick66** [comment]
Did you try?
`func setDisplayDate(date : NSDate, animated: Bool)`

**Comment by aldertc** [comment]
How do I access that function as its not in any of the code?

**Comment by mmick66** [comment]
It is used in the example when setting the date picker at the bottom, look at the ViewController.swift
```
@IBAction func onValueChange(picker : UIDatePicker) {
    self.calendarView.setDisplayDate(picker.date, animated: true)
}
```

**Comment by aldertc** [comment]
Thanks - turns out I had an older version downloaded which didn't have that functionality. Since updating I found the func and it's working a treat.

Thanks ever so much for your help - really appreciate it.

**Comment by mmick66** [comment]
No worries
