### ISSUE TITLE
Instance of new calendar and date selection

### ISSUE THREAD

**Issue by mobile-it** [mmick66/CalendarView#30]
Hi. 

I have problem with multiselection..
I have button that navigates me to the next screen, the first instance of class works perfectly fine, but when dismiss View Controller and press button one more time, I can't deselect cell, when multi selection is enabled.

**Comment by mobile-it** [comment]
The second instance of CalendarView is not entering didSelectItemAt.

**Comment by mmick66** [comment]
It sounds like a complicated scenario. Could I ask you to drop your project (or a simplified version of) here as a zip file? I will have a look.
