### ISSUE TITLE
'setDisplayDate' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by eitanaviv** [mmick66/CalendarView#38]
Hi there,
I want to start using your calendar and i followed the instructions, but something seems to be wrong.
Not sure if it's me or not, but here's what i've done:
1. Added your library via Pod.
2. Added UIView to my storyboard as follows:
![screen shot 2018-06-03 at 18](https://user-images.githubusercontent.com/35567702/40887953-f53b857c-6758-11e8-828b-a97c5046e1be.png)
3. Entered the following codes and got `'setDisplayDate' is inaccessible due to 'internal' protection level`:
```swift
import KDCalendar

@IBOutlet weak var calendarView: CalendarView!

override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)

    let today = Date()
    self.calendarView.setDisplayDate(today, animated: false)
}
```

Edit:
I'm using Xcode 9.4 (latest) and latest swift.

Any idea what's wrong?
Thanks :)

**Comment by RNUK** [comment]
Same issue accessing the calendar in startDate and endDate functions.

**Comment by eitanaviv** [comment]
Hi @RNUK , thanks for your response.
I imported the library manually and fixed it, but what's the point if you have CocoaPods.
Thanks anyway!

**Comment by mmick66** [comment]
I apologize for this. The truth is that I was never comfortable with CocoaPods. @RNUK : Can you please do a pull request with that change? Thank you...
