### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [mmick66/CalendarView#40]
Good day @mmick66  I am a graphic designer and an open source enthusiast  and i would like to contribute a logo design for your good project for free. If you will permit me, I will begin my design asap. Thanks and best regards! - Tobaloidee

**Comment by mmick66** [comment]
Well... Cant's say no to a free proposal!

Let me know when you finish and I will be sure to use it for my calendar. 

Thank you...

**Comment by Tobaloidee** [comment]
Yes Sir! will begin my design and post it here asap..thanks!

**Comment by Tobaloidee** [comment]
here's what i came up with @mmick66  i hope you like it!! Still open for modifications and adjustments.

in 3 different color variation options

![pres-01](https://user-images.githubusercontent.com/36028424/42092592-031b86dc-7bdc-11e8-8355-74f137b71f1a.png)

**Comment by mmick66** [comment]
Looks good! I am sorry I did not tell you but the product name is Karmadust. CalendarView is only the repo name. I will change it for the title as well.

**Comment by Tobaloidee** [comment]
Okay Sir..i will edit and make it karmadust..which color do you prefer?

**Comment by Tobaloidee** [comment]
here Sir, or it's just "Karmadust" ?  and which color?

i'll maka a PR and upload the files once its final :)

![pres-01-01](https://user-images.githubusercontent.com/36028424/42124670-badb3c28-7c99-11e8-9afe-08db69a8d513.png)

**Comment by mmick66** [comment]
Just “Karmadust”... thank you!

**Comment by Tobaloidee** [comment]
![pres-01-01-01](https://user-images.githubusercontent.com/36028424/42124693-52c7aae4-7c9a-11e8-9bb3-751030205d15.png)

which color will i upload Sir?

**Comment by Tobaloidee** [comment]
Hi @mmick66  I made variations and different file formats of your logo for future use and you can download it on the link below

[Ai-PNG-SVG](https://drive.google.com/drive/folders/1G9RWydnilb8qFcqfmugloguLIHuQ7yQx)

best regards!
