### ISSUE TITLE
Is there a way to add events without synchronizing with EKEventStore

### ISSUE THREAD

**Issue by aadjemonkeyrock** [mmick66/CalendarView#46]
I've events in the data store and I don't want to ask for permission on the EventStore but still show them. Is there a way to do this?

**Comment by aadjemonkeyrock** [comment]
@mmick66  Thank you. I figured out a good way of doing it by manually creating CalendarEvents and adding them to the calendar. In the example it worked fine, but not after installing the cocoapod. I had to make some components public for it to work. I send you a pull request with some changes.

**Comment by mmick66** [comment]
Hey, thanks!

**Comment by aadjemonkeyrock** [comment]
@mmick66 It would be great if you can create a new release with a new podspec. So everyone using cocoapods gets the latest version.

Thx.

**Comment by mmick66** [comment]
Done!
