### ISSUE TITLE
Adding an event causes internal mix-up with date

### ISSUE THREAD

**Issue by philzeey** [mmick66/CalendarView#49]
I'm not sure how exactly because I've debugged it all the way down to Eventsmanager.add function and the date stays correct all the way through. However, if you stop the program and go look at your iOS calendar the date is always a day before. Aka - I'll make an event for September 25th, but in the iOS calendar it shows September 24th at 6 - 7 PM. 

So when I restart the application and calendarView.loadEvents() is called it now shows the 24th, not the 25th. Maybe someone else could shed some light on the issue as I've traced it back but maybe not as far as I need to? Btw I'm on iphone X simulator if that matters.

Update:

So I ended up adding 9 hours to the didLongPressDate function and it 'fixed' it. Not really a fix though. Essentially what is happening is that it's not taking into account the timezone change. When you add a date using the didLongPressDate it automatically sets the date for example, startDate: 2018-09-27 00:00:00, endDate 2018-09-27 01:00:00. Which is fine but when it adds it to my Mountain Time/USA timezone it adds to to 2018-09-26 18:00:00 to 2018-09-26 19:00:00. Hence why adding 9 hours 'fixed it' but not really.

It seems that this is explained on the Readme. missed that woops. However, Is there a way to fix this problem so that it pertains to each individuals users time zone? Or whats the best way to go about this?

**Comment by philzeey** [comment]
Update:

So I ended up adding 9 hours to the didLongPressDate function and it 'fixed' it. Not really a fix though. Essentially what is happening is that it's not taking into account the timezone change. When you add a date using the didLongPressDate it automatically sets the date for example, startDate: 2018-09-27 00:00:00, endDate 2018-09-27 01:00:00. Which is fine but when it adds it to my Mountain Time/USA timezone it adds to to 2018-09-26 18:00:00 to 2018-09-26 19:00:00. Hence why adding 9 hours 'fixed it' but not really. 

Is there a way to fix this problem so that it pertains to each individuals users time zone?

**Comment by mmick66** [comment]
Thank you, I will look into it.

**Comment by mmick66** [comment]
Can you please check if it works now? Thanks!
