### ISSUE TITLE
Use of undeclared type 'CalendarView'

### ISSUE THREAD

**Issue by iamir4g** [mmick66/CalendarView#51]
hi 
I get this error "Use of undeclared type 'CalendarView " I clean project and rebuild a project.
<img width="262" alt="screen shot 1397-07-09 at 14 00 00" src="https://user-images.githubusercontent.com/10659860/46283782-535fae80-c582-11e8-8ba5-fa5f3424f085.png">
my class :
<img width="491" alt="screen shot 1397-07-09 at 14 01 53" src="https://user-images.githubusercontent.com/10659860/46283863-991c7700-c582-11e8-8df0-a6df64954e57.png">

thank for helping

**Comment by mmick66** [comment]
What versions are you using? (iOS, Swift etc.)

**Comment by iamir4g** [comment]
iOS 12 and swift 4

**Comment by mmick66** [comment]
Cool, so it was an installation problem... Can you please elaborate in what you mean Module Dropdown?

**Comment by mmick66** [comment]
Thank you so much!

**Comment by alexkitto** [comment]
You're welcome :)
