### ISSUE TITLE
Previous date change issue

### ISSUE THREAD

**Issue by umretiya** [mmick66/CalendarView#54]
Hello, 

today i have implemented CalendarView in Swift 4 & . it is working smoothly.here i have one issue that previous month is going for only 2 month from today as i am working on logs app. so i need to pick more than 2 month old date so can you can you tell me how to resolve this issue, will be good if it solved quickly or can you just give me hint how can i change **startDateCache** ?
Thank you..

**Comment by mmick66** [comment]
Don't do anything to the **startDateCache**, you need to implement the delegate like I have written in the readme file...

> protocol CalendarViewDataSource {
>     func startDate() -> NSDate // UTC Date
>     func endDate() -> NSDate   // UTC Date
> }

**Comment by umretiya** [comment]
Thank u so much Sir, got a great help..!!
