### ISSUE TITLE
Wrong date for "Today cell"

### ISSUE THREAD

**Issue by Appswage** [mmick66/CalendarView#55]
The default calendar highlights the current date in a red shade. However, the current date is not always correct, I believe because of time zone. In order to display the proper current date on the calendar itself, is there a method I am missing to provide this or should the library in this case get the current time zone in order to color the appropriate current date?

**Comment by MilesV64** [comment]
Seems like a more general issue than just the 'today' cell, programmatically selecting a cell based on date will also be wrong sometimes.

**Comment by felipedemetrius** [comment]
Fixed in https://github.com/mmick66/CalendarView/pull/70
