### ISSUE TITLE
Cell Selected Colors not Hooked Up

### ISSUE THREAD

**Issue by Appswage** [mmick66/CalendarView#58]
Neither cellSelectedTextColor or cellSelectedColor work. Searching the code and, outside of the definition for these variables, they are never used.

**Comment by Appswage** [comment]
@mmick66 -  Thanks! Any news on this one or the "today" bug logged earlier last month? Appreciate it.

**Comment by MilesV64** [comment]
`override open var isSelected : Bool {
        didSet {
            switch isSelected {
            case true:
                self.bgView.layer.borderColor = CalendarView.Style.cellSelectedBorderColor.cgColor
                self.bgView.layer.borderWidth = CalendarView.Style.cellSelectedBorderWidth
                self.bgView.backgroundColor = CalendarView.Style.cellSelectedColor
                self.textLabel.textColor = CalendarView.Style.cellSelectedTextColor
            case false:
                self.bgView.layer.borderColor = CalendarView.Style.cellBorderColor.cgColor
                self.bgView.layer.borderWidth = CalendarView.Style.cellBorderWidth
                self.bgView.backgroundColor = CalendarView.Style.cellColorDefault
                self.textLabel.textColor = CalendarView.Style.cellTextColorDefault
            }
        }
    }`

This fixes it, this is in the CalendarDayCell class.
