### ISSUE TITLE
Programmatically selecting cells and scrolling to date don't work in viewDidLoad

### ISSUE THREAD

**Issue by MilesV64** [mmick66/CalendarView#59]
Calling calendarView.setDisplayDate and calendarView.selectDate in viewDidLoad, where I set up the calendarview itself doesn't do anything. Only works if I program in a delay. Am I doing something wrong, should those methods be put somewhere else?

**Comment by johnCbogil** [comment]
I'm experiencing the same problem

**Comment by johnCbogil** [comment]
Hey @mmick66, do you have any advice for how to solve this issue?

I would like to be able to call `calendarView.selectDate` inside of `viewDidLoad` because when I call `selectDate` inside of `viewDidAppear`, the dates are deselected on alternating appearances. 

Thanks for your help

**Comment by MilesV64** [comment]
It's something to do with the collectionview not populating yet, you could experiment with calling selectDate in viewDidLayoutSubviews, but you'd have to be careful about how multiple calls would affect it.

Looking through it, it seems the collectionview doesn't use a data source thats separate from the cells themselves to track states like selected, so everything is dependent on how the collectionview loads/deques the reusable cells which leads to issues like this.

**Comment by mmick66** [comment]
At the moment it's the way I've designed the calendar that makes it unable to catch the ViewController methods. My decision (for better or worst) was based on my initial idea to have a drag and drop component through Interface Builder, with minimal setup.
