### ISSUE TITLE
calculateDateBasedOnScrollViewPosition

### ISSUE THREAD

**Issue by cesarmtz93** [mmick66/CalendarView#6]
In your function calculateDateBasedOnScrollViewPosition once you set it up as Vertical it won´t update the headerView.monthLabel.text because you have it set up like 
        var page : Int = Int(floor(self.calendarView.contentOffset.x / cvbounds.size.width))

so in order for it to work once it's set up vertically it should be

```
    var page : Int = direction == .Horizontal ? Int(floor(self.calendarView.contentOffset.x / cvbounds.size.width)) : Int(floor(self.calendarView.contentOffset.y / cvbounds.size.height))
```

**Comment by mmick66** [comment]
Many thanks my friend!
