### ISSUE TITLE
Grey out non-selectable dates

### ISSUE THREAD

**Issue by jeet-chanchawat** [mmick66/CalendarView#60]
![greydates](https://user-images.githubusercontent.com/2392078/52835619-2cf37780-310d-11e9-9c4f-fffd42d64934.png)

Please add this feature based on the method "func calendar(_ calendar: CalendarView, canSelectDate date: Date) -> Bool "

**Comment by CearsKhush** [comment]
Hey @jeet-chanchawat, Did you get any solution on this I want to do the same, Please Help!

**Comment by mmick66** [comment]
I will fix this today. Do you mean that the dates that are before the `startDate` should be grayed out?
