### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by evgenijromanishyn** [mmick66/CalendarView#76]
Everything is perfect.
The name of the month is not correct in Russian. I can not change the title, this is a private method.
To display the title correctly, I recommend using something like this:

```
func displayDateOnHeader(_ date: Date) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "LLLL yyyy"
        self.headerView.monthLabel.text = dateFormatter.string(from: date)
        
        self.displayDate = date
}
```

**Comment by mmick66** [comment]
This is provided for in:

```
public protocol CalendarViewDataSource {
    func startDate() -> Date
    func endDate() -> Date
    /* optional */
    func headerString(_ date: Date) -> String?
}
```

If you implement the headerString method you can return a custom string according to the date passed.
