### ISSUE TITLE
Initial date issue

### ISSUE THREAD

**Issue by JeKomme** [mmick66/CalendarView#8]
when i change the start date, the initial view change also, like it shows 2015 instead of the current year

**Comment by mmick66** [comment]
Thank you, can you please be more specific? Do you change the start date dynamically? (i.e. after the initial loading and during the running of your app). Can you please specify the dates so I can recreate it? ex. "I start with today's date and then I change it to a month ago and then this and that happens".

Thank you!

**Comment by JeKomme** [comment]
okay, that's how i implement the startDate:

    func startDate() -> NSDate? {
        let dateComponents = NSDateComponents()
        
        dateComponents.year = -1 // To be able to scroll to 1 year in the past "to 2015"
        
        let today = NSDate()
        let theCurrentMonth = self.calendarView.calendar.dateByAddingComponents(dateComponents, toDate: today, options: NSCalendarOptions())
        
        
        return theCurrentMonth
        
    }

**Comment by mmick66** [comment]
That looks fine to me. What exactly is the problem? Can you please specify the steps you took to reproduce it?

**Comment by JeKomme** [comment]
Just run it, and u'll find the calendar opens with November 2015 instead of November 2016.. it's supposed to open with today's date and 2016 not 2015, u got me ?

**Comment by mmick66** [comment]
Well, you are setting it to start on November 2015:

`dateComponents.year = -1`

What you want is to be able to scroll to November 2015, but actually display today's date (November 2016). In this case use the code snippet I just pasted above. It should do your job.

**Comment by JeKomme** [comment]
Great, two more quick questions:
1- what is this line for ? 
    self.datePicker.setDate(date, animated: false)
2- Still shows up with November 2015, but when i scroll to any direction for at least once and scroll back it shows the right date November 2016

**Comment by mmick66** [comment]
1. The date picker component is independent of the calendar, and chances are you are not going to use one. There is no connection between the calendar and that, it is just for show and so needs to be updated separately.
2. Did you put the code in the right place? I just pushed a new change in the repo which should do just that, so please checkout again and test.

**Comment by JeKomme** [comment]
1-yes i see)
2-Yes, and it works just fine and it outputs to the console the right date when i select one, the only problem is the header, it shows at the beginning November 2015 , then after one scroll to any direction, it changes to November 2016

**Comment by mmick66** [comment]
Check it now... I believe I fixed it.

**Comment by JeKomme** [comment]
Awesome! thank u i'll check it out again and hopefully it works, again thank u:)
