### ISSUE TITLE
When would you release next version?

### ISSUE THREAD

**Issue by kyonge** [mmick66/CalendarView#80]
Hello, I'm using CalendarView with big appreciate.

The latest version is 1.6.5 now, and I guess there would be an update about locale in next version.
When would you update it?

**Comment by gsoykan** [comment]
Still waiting for the next release with the locale. I suggest you would update your readme in case you are not updating the pod itself.

**Comment by mmick66** [comment]
I am back to work on this project (after a looong time away from it). Any advice would be helpful. Could you please tell me exactly what you mean with the locale? Forgive me but I need to look into my code like I would look into someone else's by now. Thanks!

**Comment by mmick66** [comment]
I just published pod version 1.7.2... Please let me know if you experience any problems by opening a new issue.
