### ISSUE TITLE
How to validate date selection

### ISSUE THREAD

**Issue by CearsKhush** [mmick66/CalendarView#83]
Hello, Thank you for this awesome library I am using this date picker but I need to disable some date and allow user to select date after particular date for example If today is 6 Aug the I want to allow user to select date after 2 days which means user cant select 7 and 8 Can any one please help me with this?

**Comment by mmick66** [comment]
I have recently added this ability. Have a look at the latest version and the [section on how to use it](https://github.com/mmick66/CalendarView#graying-out-days).
