### ISSUE TITLE
Calling goToNextMonth() sometimes shows the wrong month

### ISSUE THREAD

**Issue by ojseven** [mmick66/CalendarView#84]
Calling goToNextMonth() sometimes shows the wrong month in header. This can be repeated by using it going from December 2019 to January 2020

**Comment by mmick66** [comment]
Can you please provide me with your `start` and `end` date so I could replicate?

**Comment by ojseven** [comment]
Sure thanks mmick66, great library by the way. 

`func setCalendarStyle(){
        CalendarView.Style.cellSelectedColor = MStyle.secondaryAccent
        CalendarView.Style.cellColorDefault = MStyle.secondaryBackground
        CalendarView.Style.cellBorderColor = .clear
        CalendarView.Style.cellSelectedBorderColor = .clear
        CalendarView.Style.cellSelectedTextColor = .white
        CalendarView.Style.cellShape                = .round
        CalendarView.Style.cellTextColorToday = MStyle.tertiaryAccent
        CalendarView.Style.headerTextColor = .white
        calendarView.multipleSelectionEnable = false
        CalendarView.Style.firstWeekday = .sunday
        CalendarView.Style.headerBackgroundColor = MStyle.secondaryAccent
        CalendarView.Style.cellTextColorWeekend = MStyle.secondaryText
        CalendarView.Style.locale                   = Locale(identifier: "en_US")
        CalendarView.Style.timeZone                 = TimeZone(abbreviation: "UTC")!
    }`

`extension CalendarViewController : CalendarViewDelegate {
    func calendar(_ calendar: CalendarView, didLongPressDate date: Date, withEvents events: [CalendarEvent]?) {
        
    }
    
    func calendar(_ calendar: CalendarView, didScrollToMonth date: Date) {
        let cal = Calendar.current
        let currentYear = cal.component(.year, from: Date())
        let currentMonth = cal.component(.month, from: Date())
        let selectedYear = cal.component(.year, from: date)
        let monthPlus = cal.date(byAdding: .month, value: 1, to: date)
        let selectedMonth = cal.component(.month, from: monthPlus!)
        let dateInFuture = yearPlus
        if currentYear == selectedYear && currentMonth == selectedMonth {
            vLeftIndicator.isHidden = true
        }else{
            vLeftIndicator.isHidden = false
        }
        if dateInFuture <= date {
            vRightIndicator.isHidden = true
        }else{
            vRightIndicator.isHidden = false
        }
    }
    
    func calendar(_ calendar: CalendarView, didSelectDate date: Date, withEvents events: [CalendarEvent]) {
        self.vTimePicker.isHidden = false
    }
    
    func calendar(_ calendar: CalendarView, canSelectDate date: Date) -> Bool {
        return true
    }
    
    func calendar(_ calendar: CalendarView, didDeselectDate date: Date) {
        self.vTimePicker.isHidden = true
    }
    
}

extension CalendarViewController : CalendarViewDataSource {
    func headerString(_ date: Date) -> String? {
        return nil
    }
    
    func startDate() -> Date {
        return Date()
    }
    
    func endDate() -> Date {
        return yearPlus
    }
    
}`

` @IBAction func actionNextMonth(_ sender: Any) {
        calendarView.goToNextMonth()
    }
    
    @IBAction func actionPreviousMonth(_ sender: Any) {
        calendarView.goToPreviousMonth()
    }`

called in view did load
`yearPlus = calendarView.calendar.date(byAdding: .year, value: 1, to: Date())!`

Please let me know your findings, I did some troubleshooting for quite some time yesterday and couldn't seem to figure it out. 

I've also slightly modified the library so include a "headerBackgroundColor" so I could change the header color. This would be a great addition to the standard Style options.

**Comment by mmick66** [comment]
If you think it’s worth adding. Do a pull request with the header bg code. On the other issue, I am currently away on holidays and I will get back on Thursday

**Comment by ojseven** [comment]
Pull request added for the header background color option. Thanks!

**Comment by mmick66** [comment]
Merged. If the other problem persists, please open a new issue. Thanks!
