### ISSUE TITLE
Can't access addEvent

### ISSUE THREAD

**Issue by arjun20** [mmick66/CalendarView#89]
![Screenshot 2019-09-14 at 5 37 00 PM](https://user-images.githubusercontent.com/3456184/64907901-6f6a4a80-d716-11e9-927f-4ff2aa527a6a.png)

**Comment by arjun20** [comment]
Im Use Xcode Version 11.0 beta 3 (11M362v), and swift 
I'm getting trouble to use addEvent functionality

**Comment by mmick66** [comment]
<img width="765" alt="Screenshot 2019-10-05 at 11 15 08" src="https://user-images.githubusercontent.com/342781/66252240-9dfda300-e761-11e9-9946-1bc18eebe91c.png">

I just saw that someone added this flag... some pull request I did not check properly. It's not a bad idea... but still, it might be the root of your problem. Please let me know...

**Comment by mmick66** [comment]
I have just added the appropriate [instructions](https://github.com/mmick66/CalendarView#events) in the README file. Apologies for not spotting it earlier. Enjoy.
