### ISSUE TITLE
Week view with events

### ISSUE THREAD

**Issue by HPRaval** [mmick66/CalendarView#9]
Hi Michael...first of all great tutorial. I have modified your code as per my requirement and works like a charm. Can you please help me to create week view control with the same. I want to list events as in default calendar app.

**Comment by mmick66** [comment]
Hello HPRaval, it seems that you are asking for a couple of days work from me haha. I think you need to try it out yourself and if you get anywhere you could fire a pull request and incorporate it. Good luck!
