### ISSUE TITLE
crash  on setDisplayDate

### ISSUE THREAD

**Issue by MSawalha** [mmick66/CalendarView#90]
```
  public func setDisplayDate(_ date : Date, animated: Bool = false) {
        
        guard (date >= startDateCache) && (date <= endDateCache) else { return }
        self.collectionView.setContentOffset(self.scrollViewOffset(for: date), animated: animated)
        self.displayDateOnHeader(date)
    }
```
     is causing a crash 

**Thread 1: EXC_BAD_ACCESS (code=2, address=0x1d00399c0)**

**Comment by mmick66** [comment]
Could you provide a complete crash log?

**Comment by ahmetsina** [comment]
@MSawalha I got same issue but I realized that I didn't set KDCalendar as Module in Interface Builder -> Identity Inspector -> Custom Class. I fixed my issue like this way.

**Comment by mmick66** [comment]
Ok, that is great. Could you please tell me exactly how you fixed it so I can amend the README? First, did you install it via Pods or manually? Then, what did have to set?

**Comment by ahmetsina** [comment]
[As you mentioned in here](https://github.com/mmick66/CalendarView#setup) " If doing the latter, make sure that the Module is selected to be KDCalendar." You can add **"Otherwise it may cause a crash."**  after

**Comment by mmick66** [comment]
Ok, so I had mentioned it... pheww... ;-) Thank for commenting and using my library!

**Comment by durgapt** [comment]
@mmick66  First of all Thanks for this wonderful library. I am getting same crash while setting DisplayDate. Here I already setup Module to be KDCalendar. 

Crash:
`0   libswiftFoundation.dylib      	0x00000001d59ed760 getEnumTagSinglePayload for PropertyListEncoder._Options + 8 (<compiler-generated>:0)
1   libswiftCore.dylib            	0x00000001ac68e478 initializeWithCopy for ClosedRange<>.Index + 60 (<compiler-generated>:0)
2   SlowCOVIDNC                   	0x0000000103084dfc _hidden#746_ + 52 (__hidden#110_:0)
3   SlowCOVIDNC                   	0x0000000103089c7c __hidden#547_ + 60 (__hidden#1199_:106)
4   SlowCOVIDNC                   	0x0000000103089c7c CalendarView.setDisplayDate(_:animated:) + 348 (__hidden#1199_:419)
5   SlowCOVIDNC                   	0x0000000102f6c96c viewDidAppear + 60 (TestViewController.swift:69)`

Code:
`override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        let today = Date()
        calendarView.setDisplayDate(today, animated: false)
    }`
