### ISSUE TITLE
CalendarView.Style.cellColorToday  NOT work!

### ISSUE THREAD

**Issue by yinzixie** [mmick66/CalendarView#93]
Whatever i set, "today cell" only show the default color! (the text color is work)
![Screen Shot 2019-09-22 at 9 36 51 pm](https://user-images.githubusercontent.com/48106713/65386593-20a95a00-dd81-11e9-8383-75bcea25cc98.png)

![Screen Shot 2019-09-22 at 9 35 12 pm](https://user-images.githubusercontent.com/48106713/65386572-e049dc00-dd80-11e9-98dd-0b31003ac8ad.png)

I think this area override the background color:
![Screen Shot 2019-09-22 at 9 34 15 pm](https://user-images.githubusercontent.com/48106713/65386562-c4ded100-dd80-11e9-8a4f-9be03d2d3fbf.png)

can you fix it? or anything i did wrong?

**Comment by mmick66** [comment]
I am sorry for the delay. Hope that helps you still...
