### ISSUE TITLE
Disable Selection of Weekend - Input day

### ISSUE THREAD

**Issue by ezemartinezna** [mmick66/CalendarView#94]
Hi mmick66, first of all thanks for this awesome calendar!
I need a help to know how to disable the selection of the weekend... For example Sundays and Monday for every month.
It is possible? 
Sorry if not...
Thank you very much for your time.
Regards
Ezequiel.

**Comment by mmick66** [comment]
Yes... the calendar delegate has a method for that
```
func calendar(_ calendar : CalendarView, canSelectDate date : Date) -> Bool
```
