### ISSUE TITLE
Need to set different colour for selected cell background

### ISSUE THREAD

**Issue by kavin06** [mmick66/CalendarView#96]
Any one please give solution, In my project I need to set different background cell color for selected date.

**Comment by mmick66** [comment]
`style. cellSelectedColor = UIColor.red`

**Comment by kavin06** [comment]
func calendar(_ calendar: CalendarView, didSelectDate date: Date, withEvents events: [CalendarEvent]) {

// Here I need to change selected date cell color
}

Two cell is Yellow color another two cell is blue color like that I need to change.

**Comment by mmick66** [comment]
You need to set the style at the beginning, not dynamically... Do you actually mean that you want to have a different color for every cell selected?

**Comment by kavin06** [comment]
Yes, Need different color for every cell selected.

**Comment by mmick66** [comment]
I am sorry but you can't do that with the currect code base, it's really something I never though about...
